module.exports = {
  trailingComma: 'all',
  tabWidth: 2,
  singleQuote: true,
  semi: true,
  importOrder: [
    '^(next/(.*)$)|^(next$)|^(react$)|^(react/lib$)|^(react-dom$)|^(react-dom/lib$)',
    '<THIRD_PARTY_MODULES>',
    '^@title/(.*)$',
    '^@common/(.*)$',
    '^@ui/(.*)$',
    '^@hooks/(.*)$',
    '^@services/(.*)$',
    '^@utils/(.*)$',
    '^@interfaces/(.*)$',
    '^@enums/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
